### ISSUE TITLE
Add support for file, function and line logging

### ISSUE THREAD

**Issue by milancermak** [getsentry/sentry-swift#10]
The previous client, raven-swift, has a way how to capture messages with function name, file name and line number. This is super helpful information to have for logged events. Can you please add this functionality to this client too?

**Comment by joshdholtz** [comment]
This is currently being worked on by @ahti in #12 🙌

**Comment by joshdholtz** [comment]
I kind of lied on previous comment 😇  We currently don't have a good format for single frames on the server side and this also runs into some issues with symbolication of the code. This is being discussed with the team in the future on how to handle properly so keeping open for now.

**Comment by edenman** [comment]
Any progress on this?  Should I just construct an `Event` and populate a single-frame Stacktrace myself?

**Comment by joshdholtz** [comment]
@edenman Support for this is being added into #59 but there are some server side things that need to get taken care of first for this to work (since it has to go through the desymbolification process) in order to work properly 😇

**Comment by edenman** [comment]
@joshdholtz 🙌

**Comment by HazAT** [comment]
Hey guys ... checkout the latest release `1.3.0` ... You can send a stacktrace with your event.
https://docs.sentry.io/clients/cocoa/advanced/#change-event-before-sending-it
