### ISSUE TITLE
使用sentry是出行了闪退

### ISSUE THREAD

**Issue by loumzy** [getsentry/sentry-swift#103]
使用sentry是出行了闪退
(https://cloud.githubusercontent.com/assets/8309821/21491742/e577017c-cc39-11e6-9d70-30236634f3fe.png)

**Comment by HazAT** [comment]
Please make sure you have the latest version `1.3.4` installed, we fixed a bug regarding your crash.

**Comment by HazAT** [comment]
Please update to the latest version `1.4.0` .. the problem should be fixed there.
