### ISSUE TITLE
Crash with dyld: Library not loaded when added using Carthage

### ISSUE THREAD

**Issue by tombell** [getsentry/sentry-swift#104]
Xcode 8.2.1
Swift 3.0.2
macOS Cocoa Application

**Cartfile**

```
github "getsentry/sentry-swift" "1.3.4"
```

**Cartfile.resolved**

```
github "kstenerud/KSCrash" "1.11.2"
github "getsentry/sentry-swift" "1.3.4"
```

Added to **Embedded Binaries** dragging the `.framework` files from `./Carthage/Build/Mac`:

<img width="865" alt="screen shot 2016-12-27 at 17 45 28" src="https://cloud.githubusercontent.com/assets/129327/21505110/4964448e-cc5c-11e6-8dd5-db8f80a6b29a.png">

Before adding any code to initialise and use Sentry in the project, I use <kbd>cmd</kbd>+<kbd>r</kbd> to run within Xcode, and the following crash happens when it runs:

```
dyld: Library not loaded: /Library/Frameworks/KSCrash.framework/Versions/A/KSCrash
  Referenced from: /Users/tombell/Library/Developer/Xcode/DerivedData/Stark-fvellvhblgfvyaafoghwfsmjybsp/Build/Products/Debug/Stark.app/Contents/MacOS/Stark
  Reason: image not found
```

**Build Settings** for *"Search Paths"*:

<img width="940" alt="screen shot 2016-12-27 at 17 48 52" src="https://cloud.githubusercontent.com/assets/129327/21505174/ce3e9c4a-cc5c-11e6-9fd8-7712ba5557d4.png">

If there is anything other information I can help provide, please let me know.

**Comment by HazAT** [comment]
Hey @tombell 

Thank you very much for pointing this out ... we are currently working on a fix for that with KSCrash.
For you as a quick workaround you can copy the `KSCrash.framework` to `/Library/Frameworks`
This fixes the issue until we release a new version.

**Comment by HazAT** [comment]
And btw @tombell 
Thats a bug report developers dream of 👍

**Comment by HazAT** [comment]
Hey @tombell 
Can you update to `1.4.0` ... your problem should be resolved.

**Comment by tombell** [comment]
I'll give that try right now, thanks!

**Comment by tombell** [comment]
@HazAT working perfectly now. Thank you for looking into this and fixing it!
