### ISSUE TITLE
Don't require KSCrash

### ISSUE THREAD

**Issue by jkubicek** [getsentry/sentry-swift#105]
We are using Crashlytics for crash reporting, so we don't need to use Sentry's crash reporting tools. It would be nice if we could add the Sentry framework to our app without having to link the KSCrash framework.

**Comment by jkubicek** [comment]
Just the logging features.

**Comment by HazAT** [comment]
You could just not call `SentryClient.shared?.startCrashHandler()` then KSCrash will not be initialized. 
But we currently do not have to plan to not require KSCrash at all.
