### ISSUE TITLE
Include CFBundleVersion in Sentry's releaseVersion?

### ISSUE THREAD

**Issue by leah** [getsentry/sentry-swift#112]
I'm using TestFlight to release beta versions of my app and incrementing the `CFBundleVersion` (the build number) as well as `CFBundleShortVersionString` (the version number).

Sentry only seems to be reporting the `CFBundleShortVersionString` which isn't helpful if I've only incremented the `CFBundleVersion`. Could the `CFBundleVersion` be included in the concept of an app version as well?

**Comment by HazAT** [comment]
Thanks for pointing that out ... We will add this in the next release.

**Comment by leah** [comment]
Perfect! Thanks so much. This will help us out a lot.

Will the build number factor into Sentry's "Resolved in next release" feature? I'd be for it, because minor build number increments are often bug fixes.

**Comment by HazAT** [comment]
@leah 
I am not sure if we will add it to the "Resolved in next release" feature but I will bring it up for discussion.
https://github.com/getsentry/sentry/pull/4781

**Comment by leah** [comment]
No worries. It's not super important for us... more of a "nice to have" feature. Thanks so much for the quick update!
