### ISSUE TITLE
KSCrash Has To Be Bundled Even When Not Using Crash Handling

### ISSUE THREAD

**Issue by alexwilkinson** [getsentry/sentry-swift#118]
Hi!

I want to use this library just to send custom events to Sentry using `captureEvent()`. It appeared from the documentation that enabling crash handling with `startCrashHandler()` was optional (I can't find the where this was stated, but will link it here if I do). However, even if I do not call `startCrashHandler()` in my `AppDelegate` after initializing `SentryClient`, my app crashes with the following error on startup:

```
dyld: Library not loaded: @rpath/KSCrash.framework/KSCrash
  Referenced from: /Users/alexwilkinson/Library/Developer/CoreSimulator/Devices/41BC5348-620B-4C58-BD7C-2675669D8560/data/Containers/Bundle/Application/83C27333-1C1C-418E-BB80-6C2D4B753F45/SeeClickFix.app/Frameworks/SentrySwift.framework/SentrySwift
  Reason: image not found
```

It seems that this library requires linking KSCrash even if I am not using crash handling (I'm using Carthage as my dependency manager). As soon as I add KSCrash to my Linked Frameworks and Libraries, the app doesn't crash on startup anymore.

Is there any way that the library can avoid forcing users to include a dependency that they don't end up using? Or is KSCrash more integral to how sentry-swift works than I realize?

Thanks!

**Comment by HazAT** [comment]
Hey
Currently you have to include KSCrash as well in order to use Sentry.
We are considering making in optional but it's not a top priority right now.
I will close this issue but post here again when we have done it.

**Comment by alexwilkinson** [comment]
OK sounds good!
