### ISSUE TITLE
Carthage building for version 1.4.5 or 2.0 may have problems

### ISSUE THREAD

**Issue by michaelosity** [getsentry/sentry-swift#121]
When I try to use carthage to update the dependencies, I get the following error.

*** Checking out KSCrash at "1.15.2"
Parse error: expected submodule commit SHA in output of task (ls-tree -z 1.15.2 Source/CrashProbe) but encountered:

If I set the Sentry version to 1.4.4 it works as expected.

**Comment by HazAT** [comment]
@kstenerud any idea what this could be?

**Comment by HazAT** [comment]
This should be fixed in the latest version ... please update Sentry.
