### ISSUE TITLE
Ability to configure maxCrumbs for BreadcrumbStore?

### ISSUE THREAD

**Issue by erichsu** [getsentry/sentry-swift#126]
From the Official document of Cocoa [https://docs.sentry.io/clients/cocoa/advanced/#breadcrumbs]

It said 

> The client will queue up a maximum of 20 breadcrumbs by default.

Is there any public method to change the maximum value?

**Comment by HazAT** [comment]
Hey
We will add this in the next release!

**Comment by HazAT** [comment]
Version `2.1.0` has just been release ... the `maxCrumbs` var is now exposed.
