### ISSUE TITLE
Remove Swiftlint

### ISSUE THREAD

**Issue by jkubicek** [getsentry/sentry-swift#129]
We upgraded our local version of Swiftlint and now SentrySwift won't compile because it fails a recently added rule. I *could* fix the linter issue in SentrySwift, but I feel like this is just going to be a recurring issue anytime new rules are added to Swiftlint. I'd advocate for removing the linter from Sentry and/or putting a copy of the linter directly in the Sentry project.

**Comment by vi4m** [comment]
Or just explicitly enable rules.

**Comment by HazAT** [comment]
The latest version uses `whitelist_rules` so this should no longer happen
