### ISSUE TITLE
Sentry.framework missing from Carthage/Build/iOS/

### ISSUE THREAD

**Issue by stancho-dynoden** [getsentry/sentry-swift#131]
Hi there, I am trying to get sentry via Carthage after running 
`carthage update --platform iOS`  in Terminal

this was the output: 

*** Cloning sentry-swift
*** Cloning KSCrash
*** Checking out KSCrash at "1.15.3"
*** Downloading sentry-swift.framework binary at "2.1.0"
*** xcodebuild output can be found in /var/folders/k9..........
*** Building scheme "KSCrash-iOS" in iOS.xcworkspace

then in the project directory when I try to add the frameworks, I only have the KSCrash.framework as shown in the image

![screen shot 2017-02-15 at 17 00 29](https://cloud.githubusercontent.com/assets/21221924/22985445/5933b33e-f3a0-11e6-9abe-1212b1279e81.png)

the Sentry.framework is not there!

Is there something I am missing, I am very new to using Carthage.

Thank you!

**Comment by HazAT** [comment]
Hey
Thanks for reporting this.
Indeed I see the same behaviour ... I filed a but in the Carthage repo https://github.com/Carthage/Carthage/issues/1768

To get it to work please use `carthage update --platform iOS --no-use-binaries` or consider switching to cocoapods.

**Comment by ikesyo** [comment]
That is because there are two attached frameworks of `KSCrash.framework.zip` and `Sentry.framework.zip`. But Carthage only use one framework appeared before, so you should need to remove `KSCrash.framework.zip`.

If you really need to distribute `KSCrash.framework.zip` with `Sentry.framework.zip`, you can use the following command to archive the two frameworks into one zip file:

```bash
carthage archive Sentry KSCrash --output Sentry.framework.zip
```

**Comment by HazAT** [comment]
Thanks very much for clearing that up! 💯

**Comment by stancho-dynoden** [comment]
Thank you for your replies I used @HazAT suggestion and both frameworks now appear in the Build/iOS folder but in the terminal I got these warnings: 

warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint
<module-includes>:1:1: warning: umbrella header for module 'KSCrash' does not include header 'KSCrashMonitor_System.h'
<module-includes>:1:1: warning: umbrella header for module 'KSCrash' does not include header 'KSCrashMonitor_System.h'
warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint
<module-includes>:1:1: warning: umbrella header for module 'KSCrash' does not include header 'KSCrashMonitor_System.h'
<module-includes>:1:1: warning: umbrella header for module 'KSCrash' does not include header 'KSCrashMonitor_System.h'

Then I archived them as @ikesyo said but I don't understand what are the steps after that. Or I dont have to anything after they are archived? 

Thanks Again for your time

**Comment by HazAT** [comment]
@stancho-dynoden You don't have to archive them, thats just for us to bundle it correctly.
Please look at this tutorial on how to integrate it into you app
https://www.raywenderlich.com/109330/carthage-tutorial-getting-started

**Comment by stancho-dynoden** [comment]
Thanks @HazAT and sorry for the misunderstanding
