### ISSUE TITLE
KSCrash not packaged in latest release

### ISSUE THREAD

**Issue by jeaye** [getsentry/sentry-swift#132]
Unlike the release prior, I see that the latest release is missing the KSCrash framework. I can certainly say that it's great to have that packaged and we're currently relying on it. Hopefully it was just forgotten and it'll be in the subsequent releases. For reference: https://github.com/getsentry/sentry-swift/releases/tag/2.1.1

Thanks!

**Comment by HazAT** [comment]
Hey
It's now in the same zip ... we had to do that because otherwise people who install it with Carthage cannot install it, if its not in the same zip.
So its there, just not as a separate download :)

**Comment by jeaye** [comment]
Ah, got it. Thanks!
