### ISSUE TITLE
Submission rejection with 2.1.2 from releases

### ISSUE THREAD

**Issue by bbqsrc** [getsentry/sentry-swift#134]
While I was dealing with the issues with Carthage early, I used the zip from the releases tab.

It gets rejected when uploaded.

```text
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file
'REDACTED.app/Frameworks/Sentry.framework/libswiftRemoteMirror.dylib' is not permitted. Your
app can’t contain standalone executables or libraries, other than the CFBundleExecutable of
supported bundles. Refer to the Bundle Programming Guide at
https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle
structure."
```

**Comment by HazAT** [comment]
Thanks for reporting this.
This happened because of the last change in 2.1.2 which we will revert again in 2.1.3 ...
It's currently building, will ping you when the release is ready.

**Comment by bbqsrc** [comment]
Don't stress, as I managed to get my build working with carthage earlier 😛 

Still useful for others, of course.

**Comment by HazAT** [comment]
`2.1.3` is released, please give it a try

**Comment by HazAT** [comment]
I will close this issue for now since this should be fixed
