### ISSUE TITLE
captureEvent shouldn't clear breadcrumbs

### ISSUE THREAD

**Issue by edenman** [getsentry/sentry-swift#135]
It's really unfortunate that `captureEvent` includes a call to `breadcrumbs.clear()`.  This means if there are two non-fatal errors in a short amount of time, the second one won't have the full breadcrumb history.  Why not just make the breadcrumbs array a rolling list that never gets cleared?  Would you be open to a PR to change this?

**Comment by HazAT** [comment]
We could make this an option with default, clearing the store (just so it stays the same).

**Comment by edenman** [comment]
👍

**Comment by edenman** [comment]
want a PR or you guys wanna do it yourselves?

**Comment by HazAT** [comment]
We will do it ... there is an open branch with a lot of changes, will coordinate this.
Probably still gonna be finished by tomorrow 👍

**Comment by HazAT** [comment]
We discussed it and not deleting the breadcrumbs is now the default behaviour.
See `2.1.4`

**Comment by edenman** [comment]
Thanks!
