### ISSUE TITLE
Swiftlint build phase fails when building using of Carthage

### ISSUE THREAD

**Issue by JagCesar** [getsentry/sentry-swift#137]
_Platform:_ 
- [X]  iOS 
- [ ]  tvOS
- [ ]  MacOS 
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version? 
- [ ]  No

_sentry-swift installed with:_
- [ ] Cocoapods
- [X] Carthage
- [ ] Manually

Version of sentry-swift:
**2.1.4**

---
I have following issue:

Try to build using Carthage. It fails to build.

**Steps to reproduce:**
- Add sentry-swift to Cartfile
- Build using Carthage with the following command `carthage bootstrap --use-ssh --no-use-binaries --platform ios`

**Actual result:**

```
*** Building scheme "Sentry-iOS" in Sentry.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/jagcesar/code/allihoopa/AHA/Carthage/Checkouts/sentry-swift/Sentry.xcodeproj -scheme Sentry-iOS -configuration Release -derivedDataPath /Users/jagcesar/Library/Caches/org.carthage.CarthageKit/DerivedData/sentry-swift/2.1.4 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/9c/dzt99q5d2916bfwb09pk084r0000gn/T/carthage-xcodebuild.NlBaxz.log
```

If I try to compile your project manually I get the following log:

```
…
Linting 'SentryEndpoint.swift' (34/38)
/Users/jagcesar/code/allihoopa/AHA/Carthage/Checkouts/sentry-swift/Sources/Sentry+Error.swift:12:10: error: Identifier Name Violation: Enum element name should start with a lowercase character: 'InvalidDSN' (identifier_name)
/Users/jagcesar/code/allihoopa/AHA/Carthage/Checkouts/sentry-swift/Sources/Sentry+Error.swift:13:10: error: Identifier Name Violation: Enum element name should start with a lowercase character: 'InvalidCrashReport' (identifier_name)
Linting 'Stacktrace.swift' (35/38)
Linting 'Thread.swift' (36/38)
Linting 'User.swift' (37/38)
Linting 'UserFeedback.swift' (38/38)
Done linting! Found 11 violations, 11 serious in 38 files.

** BUILD FAILED **
```

**Expected result:**
- A successful build.

**Comment by JagCesar** [comment]
Carthage runs the following command when building

`
/usr/bin/xcrun xcodebuild -project /Users/jagcesar/code/allihoopa/AHA/Carthage/Checkouts/sentry-swift/Sentry.xcodeproj -scheme Sentry-iOS -configuration Release -derivedDataPath /Users/jagcesar/Library/Caches/org.carthage.CarthageKit/DerivedData/sentry-swift/2.1.4 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build
`

Since it sets `CARTHAGE=YES` maybe we can looks for this variable in the run script phase where we run Swiftlint?

**Comment by HazAT** [comment]
Hey, Thanks yeah will do that ... makes sense.
Also will fix the linter errors.

**Comment by HazAT** [comment]
Version `2.1.5` fixes the problem

**Comment by JagCesar** [comment]
@HazAT it works like a charm now! 💯✨
