### ISSUE TITLE
Carthage update hangs at download

### ISSUE THREAD

**Issue by arun057** [getsentry/sentry-swift#141]
_Platform:_ 
- [X]  iOS 
- [ ]  tvOS
- [ ]  MacOS 
- [ ]  watchOS

_Swift:_
- [X]  Yes -> 3.1
- [ ]  No

_sentry-swift installed with:_
- [ ] Cocoapods
- [X] Carthage
- [ ] Manually

Version of sentry-swift:
**2.1.5**

---
I have following issue:

Cartage update starts downloading the framework and gets stuck.

**Steps to reproduce:**
- carthage update --platform iOS --verbose 

**Actual result:**
➜  krosskast-IOS git:(master) ✗ carthage update --platform iOS --verbose 
*** Fetching sentry-swift
*** Fetching OAuth2
*** Fetching SwiftyBeaver
*** Fetching SDWebImage
*** Checking out AudioPlayer at "c88b6f0a4ed8f43680609f3ef8df806334671056"
*** Checking out KSCrash at "1.15.3"
*** Checking out OAuth2 at "3.0.3"
*** Checking out SDWebImage at "4.0.0"
*** Downloading sentry-swift.framework binary at "2.1.5"

**Expected result:**
- Expect sentry to be checked out

**Comment by HazAT** [comment]
Hey, please try again .... something went wrong when building sentry ... we will try to improve our build process.
