### ISSUE TITLE
Apple Submission Failure.

### ISSUE THREAD

**Issue by DClark5218** [getsentry/sentry-swift#142]
Hey guys, so submitting my app to the app store recently and keep getting denied based on a IPV6 error.

I'm checking to make sure Sentry, and also KSCrash supports IPV6? It's crashing on startup when connecting to the network, and currently Sentry and KSCrash are the only modules that are actually running on startup.

I'm using sentry 1.4.3 installed by Carthage.

Appreciate the reply in advance!

**Comment by HazAT** [comment]
Can you upgrade to the latest version and see if the problem still persists?

**Comment by DClark5218** [comment]
@HazAT weird, whenever I do a Carthage update it stalls on `Downloading sentry-swift.framework binary at "2.1.7"` even when i completely remove everything but my `Cartfile`. Any idea?

**Comment by HazAT** [comment]
@DClark5218 Please try again, should work now

**Comment by DClark5218** [comment]
@HazAT this works - rebuilding and will submit and see if this fixes this issue. Thank you for the support!
