### ISSUE TITLE
Swift 3.1 - unable to import

### ISSUE THREAD

**Issue by PhiLLKross** [getsentry/sentry-swift#143]
_Platform:_ 
- [X]  iOS 
- [ ]  tvOS
- [ ]  MacOS 
- [ ]  watchOS

_Swift:_
- [X]  Yes -> 3.1
- [ ]  No

_sentry-swift installed with:_
- [ ] Cocoapods
- [X] Carthage
- [ ] Manually

Version of sentry-swift:
**2.1.6**

---
I have following issue:

I am unable to import the module. Xcode says

```
/AppDelegate.swift:11:8: Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1: /Carthage/Build/iOS/Sentry.framework/Modules/Sentry.swiftmodule/arm64.swiftmodule
```

**Steps to reproduce:**
- Import module with latest XCode with Swift 3.1

**Actual result:**
- Error building

**Expected result:**
- No build error.

**Comment by HazAT** [comment]
Please add `--no-use-binaries` to your carthage command.
This way it will use your local swift version

**Comment by PhiLLKross** [comment]
Thank you very much, that did the trick.
