### ISSUE TITLE
Swift 3.1 support!

### ISSUE THREAD

**Issue by MihaelIsaev** [getsentry/sentry-swift#147]
Hello!

I just tried to install Sentry swift framework from the latest release and Xcode said that it is compiled for Swift 3.0.2!
Where can I get Sentry.framework compiled for Swift 3.1?

**Comment by rlimberger** [comment]
Did you find a solution to this problem? We are also running into this. Thanks.

**Comment by MihaelIsaev** [comment]
v2.1.9 works good, thanks
