### ISSUE TITLE
Sentry didnt send all the logs. Only send event on first app launch.

### ISSUE THREAD

**Issue by ahmadmuhsink** [getsentry/sentry-swift#148]
_Platform:_ 
- [x]  iOS 
- [ ]  tvOS
- [ ]  MacOS 
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version? 3.0 on Xcode Version 8.2.1 (8C1002)
- [ ]  No

_sentry-swift installed with:_
- [ ] Cocoapods
- [x] Carthage
- [x] Manually

Carthage is my configuration, but I include it as subproject for helping me to debug.

Version of sentry-swift:
**2.1.8**

---
This is my debug report:

[Sentry Debug Report](https://hackmd.io/s/SkHrVBPCx)

**Comment by HazAT** [comment]
Can you set `SentryClient.logLevel = .Verbose` and send me the output after you start the app and sending some events while the app is running to daniel@sentry.io , please?!

Also can you send me your sentry URL so I can check your account if our ratelimiter is limiting your account.

**Comment by ahmadmuhsink** [comment]
@HazAT Thanks for fast response. Sure, I will provide the data and send the email in coming hour(s). I'll inform you here after I send it.

**Comment by ahmadmuhsink** [comment]
@HazAT 
I sent the logs to the provided email address.

**Comment by HazAT** [comment]
Hey, I've just looked at your logs.
It seems that some request don't go through, I've just tested it locally with many logs and it works without any problem.
Could it be that you are on a poor internet connection?

**Comment by ahmadmuhsink** [comment]
@HazAT 
Thanks for the follow up.
Our current infrastructure is required VPN and we open up specific port for sentry server to bypass that. Can that be the case? 

We will setup https for our sentry server. But until then I will try to verify if Network configuration is really the cause of this or not.

Thanks again

**Comment by HazAT** [comment]
There is a timeout on the requests, so after 30-60sek you should see failing requests which will be sent later. 
If you set `SentryClient.logLevel = .Debug` you will see all info needed (without the payload of the request).
Failed requests will be sent with the next triggered event including a 1min buffer.
Nevertheless the queue should be ready after some time even if all requests fail.
I am pretty sure there is something about your network blocking some requests, what you could try is sending just one event at a time and increase the amount until you see them start failing.

**Comment by ahmadmuhsink** [comment]
@HazAT Alright, I think you can close this issue for now, If after re-setup our network infrastructure it still happens. I will reopen the issue with extended logs. Thanks

**Comment by HazAT** [comment]
@ahmadmuhsink Please update to 2.1.11, this should fix the issue.

**Comment by ahmadmuhsink** [comment]
@HazAT Thanks. I will try that.
