### ISSUE TITLE
culprit should be cropped to 200 chars

### ISSUE THREAD

**Issue by ahti** [getsentry/sentry-swift#17]
Sending a culprit longer than 200 characters will cause sentry to fail inserting the event into the database (see [here](https://github.com/getsentry/sentry/issues/2127)).

I encountered this while throwing an exception like this:

```swift
NSException(name: NSInternalInconsistencyException, reason: "foo is bar", userInfo: nil).raise()
```

This produced a culprit like this in sentry:

```
Application threw exception NSInternalInconsistencyException: (null)
Originated at or in a subcall of _TFC7TabTool30AttributedObjectViewController14collectionViewfTCSo16UICollectionView24didSelectItemAtIndexPathCSo11NSIndexPath_T_
```

So we should probably change how the culprit for exceptions is generated (it should probably just be the last part, demangled) and truncate all culprit strings to 200 characters (we could do something like putting the full culprit string into `extra` if the original was longer than 200 characters).

**Comment by ahti** [comment]
I'll probably send a PR tomorrow changing `Event`-serialization to truncate the culprit if necessary.

**Comment by joshdholtz** [comment]
Going to close this since I'm just going to remove the culprit completely since not relevant in this client. Thanks for the work though!
