### ISSUE TITLE
Sanitize `Dictionary` Attributes

### ISSUE THREAD

**Issue by dcvz** [getsentry/sentry-swift#33]
I'm getting crashes from the SDK when one of the `Dictionary` attributes (extra, tags, etc..) contains something that can't be parsed in JSON (i.e. `NSURL`). We need a way to detect these items and sanitize them, or place a constraint on the dictionary types.

**Comment by dcvz** [comment]
Need this for an upcoming production build so am working on it currently. But any feedback on implementation is welcome :)

**Comment by dcvz** [comment]
interesting detail is that it seems to be happening when ApplicationState is 'background'

**Comment by dcvz** [comment]
GG.
<img width="1115" alt="screen shot 2016-06-02 at 12 05 54" src="https://cloud.githubusercontent.com/assets/2475932/15741673/015ea6b0-28bb-11e6-91cb-e0691c6caff0.png">

**Comment by ahti** [comment]
@dcvz have a look at [this](https://github.com/getsentry/sentry-swift/pull/12/files#diff-cc4f83888d9daf13d443e9f28f8bf419R12) in my error pr. they try to accomplish exactly that.

I had thought about implementing this behaviour as part of `EventSerializable`, but ran into limitations of the generics system (which is not to say there is no way to do it, I just didn't find one), so it's this set of functions right now.

**Comment by joshdholtz** [comment]
@ahti That is a pretty nice approach! We can probably implement something like that when your PR is already to be looked at. @dcvz's PR definitely solves the crashing issues so I will merge his because making things go 💥  is bad but it definitely should be a bit smarter 😉
