### ISSUE TITLE
Add prebuilt binaries for Carthage

### ISSUE THREAD

**Issue by soffes** [getsentry/sentry-swift#49]
This would be really great (same for KSCrash too).

**Comment by soffes** [comment]
Any word on this?

**Comment by joshdholtz** [comment]
@soffes Oh yes, sorry! I am off today but I will get to this next week 👍

**Comment by soffes** [comment]
@joshdholtz thanks! :heart:

I'd love it if it was Swift 3.0.1 :D

**Comment by HazAT** [comment]
Hey
Version https://github.com/getsentry/sentry-swift/releases/tag/1.1.0 was released with prebuilt binaries.
From now on every release will include them.
