### ISSUE TITLE
Exception filtering

### ISSUE THREAD

**Issue by nevir** [getsentry/sentry-swift#50]
I'm currently using sentry-swift in combination with raven-js on a React Native app.  When the JS bundle throws a global exception, it bubbles out to the native half of the application.  Every JS crash ends up emitting two Sentry events (one for JS, another for native). 

The native message is along the lines of `RCTFatalException: Unhandled JS Exception: <message>`

It'd be really nice if we could filter events (via a callback?), or at least via a message prefix.

**Comment by joshdholtz** [comment]
@nevir I like the idea of this! I will look into adding that in for you 😊

**Comment by nevir** [comment]
Awesome, thanks!

**Comment by HazAT** [comment]
Hey there,
I know I am a little late to the party, but we added callback block before sending an event to the server ... maybe it helpful for you.
Checkout the latest release `1.3.0` https://docs.sentry.io/clients/cocoa/advanced/#change-event-before-sending-it
