### ISSUE TITLE
captureError not working (0.3.2)

### ISSUE THREAD

**Issue by andresgarza** [getsentry/sentry-swift#53]
I'm trying to log an NSError using `captureError` yet it seems that the event is never sent. Inspecting the code, it looks like the the event is never sent given that `NSJSONSerialization.isValidJSONObject` fails.

**Comment by joshdholtz** [comment]
@andresgarza I will look in to that today for you! What version of `sentry-swift` are you using where you are seeing this?

**Comment by andresgarza** [comment]
v0.3.2

To test it, I was doing a simple `SentryClient.shared?.captureError(NSError(domain: "com.example", code: 10, userInfo: nil))`

**Comment by andresgarza** [comment]
@joshdholtz thanks!

**Comment by joshdholtz** [comment]
That example helps 😊  Hope to get a fix up for you soon!

**Comment by joshdholtz** [comment]
@andresgarza Made a PR for the fix (just waiting for tests to finish running). I will let you know when merged and releases are made and pushed out 👍

**Comment by joshdholtz** [comment]
@andresgarza Version `0.3.3` release has been created (for Carthage) and also pushed to CocoaPods (not sure how long it will take for it to show up)

**Comment by andresgarza** [comment]
@joshdholtz awesome! thanks a lot!
