### ISSUE TITLE
User info is not sent or displayed for a Fatal error

### ISSUE THREAD

**Issue by carole-lavillonniere** [getsentry/sentry-swift#57]
When I track a `Fatal` error, the user info (email and id) is not displayed in the web interface. If I change the severity to `Warning` the user info does show up.

``` swift
let event = Event.build("ErrorTest") {
  $0.level = .Fatal
  $0.tags = [:]
  $0.extra = [:]
  if let file = file, function = function {
    $0.stacktrace = Stacktrace(frames: [Frame(file: file, function: function, line: line)])
  }
}
SentryClient.shared?.captureEvent(event)
```

I am using sentry-swift version **0.3.3**.

**Comment by HazAT** [comment]
Thank you for reporting this.
Will be fixed in the release.
