### ISSUE TITLE
Swift 3.0 ?

### ISSUE THREAD

**Issue by StevenMasini** [getsentry/sentry-swift#63]
Swift 3 Release?

**Comment by joshdholtz** [comment]
@StevenMasini Its merged into master but was waiting for a fix on `KSCrash` to get passed through first. It will be released today as version `0.4.0`

**Comment by joshdholtz** [comment]
@StevenMasini There release has been made for `0.4.0` for Carthage and `0.4.0` has also been pushed to CocoaPods

**Comment by StevenMasini** [comment]
@joshdholtz okay thank you 👍
