### ISSUE TITLE
Support for Sentry User Feedback

### ISSUE THREAD

**Issue by jezell** [getsentry/sentry-swift#64]
Is this coming?

**Comment by dcramer** [comment]
We do have the ability to submit this via an API now but that would require a diff set of keys. It's possible we could simply open up DSN with on a subset of endpoints so we could easily support the feedback form in non-web

**Comment by HazAT** [comment]
WIP #77 👍

**Comment by HazAT** [comment]
Feature will be release shortly ..
stay tuned for next release coming in the next days ;)

**Comment by larsschwegmann** [comment]
Is this possible by now?
