### ISSUE TITLE
Compile time of Event.swift#serialized & Stacktrace.swift#serialized is high

### ISSUE THREAD

**Issue by gabek** [getsentry/sentry-swift#65]
Now that I've updated to Swift 3.0 I thought I'd go through and find some of the culprits of long compile times.  It seems Sentry is the top two offenders.  They are both `serialized` methods.

I only wanted to bring it up in case there is some re-jiggering of the code that could be done simply to help. 

```
7093.0ms       Pods/SentrySwift/Sources/Event.swift:145:42 @objc dynamic get {}
1070.7ms       Pods/SentrySwift/Sources/Stacktrace.swift:114:42    @objc dynamic get {}
```

**Comment by joshdholtz** [comment]
@gabek Thanks for the letting me know 😊  I will definitely do some re-jiggering of those

**Comment by HazAT** [comment]
I was able to improve the compile time quiet a bit ...
```
44.0ms       Sources/Event.swift:153:42 @objc dynamic get {}
73.0ms       Sources/Stacktrace.swift:15:23    @objc dynamic get {}
```
Will be added to 1.0 release, closing this ...
