### ISSUE TITLE
Problems with breadCrumbs and Events

### ISSUE THREAD

**Issue by scott-recker** [getsentry/sentry-swift#66]
I can't seem to get the breadcrumbs/events to report anything at all. My app is an objective-c app and we are running a self-hosted Sentry server. I get crash reports just fine, but adding breadcrumbs and/or events send nothing, as far as I can tell, to the server.

I am using the example code from the example objc project [view controller](https://github.com/getsentry/sentry-swift/blob/master/Examples/ObjCExample/ObjCExample/ViewController.m)

Is the sample code wrong/out of date? 
Any pointers would be appreciated.

**Comment by joshdholtz** [comment]
@scott-recker Sorry about the issues/confusion! I will verify that this is working for me later tonight / tomorrow but breadcrumbs are only configured to get sent on `fatal` or `error`. The current behavior does not have them getting sent up on anything else.

Can you verify that your fatal/error events don't have your breadcrumbs? Also, are you on the `0.4.0`, the latest version?

Thanks!

**Comment by scott-recker** [comment]
I am using the code from the sample app almost verbatim, except for our DSN strings. I set up a crash to happen when a button is pressed and am seeing a fatal crash in Sentry.

I have never gotten any breadcrumbs to show up no matter how I've configure thins, I've looked at the json in console while in debug mode and no hint of them there either.

https://www.dropbox.com/s/qbty1xjl1zy522g/crashSentry.png?dl=0

**Comment by joshdholtz** [comment]
@scott-recker Update is on the way! Just waiting for tests to finish

**Comment by joshdholtz** [comment]
@scott-recker Should be fixed for you in `0.4.1`

**Comment by scott-recker** [comment]
@joshdholtz This is good news, I am really looking forward to switching over to Sentry. Thanks.
