### ISSUE TITLE
Question on sending log files with crash report

### ISSUE THREAD

**Issue by scott-recker** [getsentry/sentry-swift#68]
We currently log a lot of information within our app and these log files are sent back to us through HockeyApp with crash reports. We are looking to switch to Sentry, but I can not find a way to automatically send the logs back with a crash report. Theses logs can be fairly large, up to 1 Mb. I've tried using breadcrumbs instead, but I only see the last 20 or so. 

I've also tried to send the information as a string as part of the "extra" dictionary, but again it is truncated. 

Is there a way to increase the limits of either the number of breadcrumbs reported or increasing the limit of the string sent back in an extra dict?

**Comment by HazAT** [comment]
Hey sorry for the very late reply ...
Currently we have no plans in supporting sending large amounts of data.
We aggressively trim down data in order to not make individual events too large.
https://docs.sentry.io/learn/quotas/#attributes-limits
