### ISSUE TITLE
Where are the slugs?

### ISSUE THREAD

**Issue by MaximusMcCann** [getsentry/sentry-swift#69]
Cannot find any of these parameters on the website. :/  I only see the DSN stuff, but have no idea how that would map to the items below.  Please help!
```
  upload_symbols_to_sentry(
    api_key: '...',
    org_slug: '...',
    project_slug: '...',
  )
```

**Comment by mitsuhiko** [comment]
Hi. For the record the information in the README was outdated, you should use the `auth_token` instead. The official docs are here: https://docs.getsentry.com/clients/objc

The sluts are in the URL in the sentry dash. Just navigate to the project you are looking for. First part in the URL is the org slug, second is the project slug.

**Comment by MaximusMcCann** [comment]
Appreciate the quick response.  I don't see an `auth_token` on the website.  After clicking 'details' in the DSN area, I see a `public key` and a `secret key` is it one of those?

Thank you for the help!

**Comment by dcramer** [comment]
@MaximusMcCann its at https://sentry.io/api/ (the DSNs are a special case thing for sending events)
