### ISSUE TITLE
sentry-swift is not standalone

### ISSUE THREAD

**Issue by ksm** [getsentry/sentry-swift#70]
I prefer to use libraries that are standalone: they should have no dependencies. It makes managing dependencies in your app easier.

This was the situation with `raven-swift`, but is no longer the case with `sentry-swift` which pulls in`KSCrash`.

I only use Sentry for logging, not for crash reporting. It seems like to use the logging part I now also need to drop in KSCrash into my app if I'd like to continue using it.

It would be nice if this scenario was supported.

**Comment by dcramer** [comment]
@ksm it sounds like there's a misunderstanding in what Sentry is. While you can certainly send non-crashes our platform is fundamentally designed for them. Because of that KSCrash is not only a dependency but a requirement. This is almost certainly not going to change in our official SDK.

**Comment by ksm** [comment]
Your website says "Sentry’s real-time error tracking...", and I use it to log errors or anything that I deem to be out of the ordinary (for crashes I use a different service). Is that really a misunderstanding?

**Comment by dcramer** [comment]
@ksm just the fact that you are only capturing individual cases and not using it for fatal errors is already a slightly different case. We're not going to stop supporting that, but it's not a common case and complicating the core functionality of the SDK doesn't feel worth it to me. 

What's the reason for not wanting the dependency?

**Comment by ksm** [comment]
As a rule of thumb I try to avoid adding dependencies that have their own dependencies. If two libraries use the same dependency, but with a different version, then it may lead to a conflict. In the long term I think it is easier to maintain a project when its dependencies are standalone.

The second reason is that it increases my app's size for no good reason. It's yet another framework included within the app, and one that doesn't get used at that.

**Comment by joshdholtz** [comment]
@ksm Are you planning to install via CocoaPods?

**Comment by ksm** [comment]
@joshdholtz Using Carthage.
