### ISSUE TITLE
Event tags produce an error on server

### ISSUE THREAD

**Issue by andraz-kozelj** [getsentry/sentry-swift#71]
I get this error on my self hosted Sentry. The error is:

`Discarded invalid value for parameter 'tags' Collapse
{
  "name": "tags",
  "value": [
    "function",
    "requestTasksForPatients(_:completion:)"
  ]
}`

When "function" changed to "functionName" it parses the JSON correctly.

SentrySwift: 0.4.1, Sentry 8.7.0

**Comment by joshdholtz** [comment]
@mitsuhiko Is `function` a reserved word or some sort?

**Comment by andraz-kozelj** [comment]
Figured out that much, will investigate as an option to propose the fix. Since I am not familiar with the internal JSON processing, it might take some time, but I think that producing an error in this case is a bit awkward.
We're talking about string literals and a user expects them to be transferred, not processed.

**Comment by joshdholtz** [comment]
@andraz-kozelj Agreed. I don't know much about the how the backend works (I only work on client SDK side fo things) so waiting on a response from @mitsuhiko to see if (and why) using `function` would do this.

**Comment by mitsuhiko** [comment]
I'm not actually sure. Pretty sure it did not used to be special at least.

**Comment by HazAT** [comment]
I just tested it, it is actually the cast ...
I created an issue on the sentry repo, closing this here because its not related to swift
Thank you for reporting!
https://github.com/getsentry/sentry/issues/4524
