### ISSUE TITLE
Full Stack Trace without a crash?

### ISSUE THREAD

**Issue by timbroder** [getsentry/sentry-swift#79]
I'm reading through the discussion in https://github.com/getsentry/sentry-swift/issues/10, but is there a way to attach a human readable stack trace to an Event or Message?

Something that will give more info than NSThread.callStackSymbols()? Or do I need to process that myself and attach as an extra?

I am uploading symbols to sentry as part of my build

Thanks!

**Comment by HazAT** [comment]
Hey!
Currently you would have to do it by yourself by adding extras.

We talked about it internally, the server already supports this we just didn't have time to add the functionality to the swift client.
It's on the roadmap for the next release, I will leave this issue open to keep you posted!

**Comment by HazAT** [comment]
@timbroder So its finally done with version `1.3.0` ... checkout the docs for how to use it
https://docs.sentry.io/clients/cocoa/advanced/#adding-stacktrace-to-message

If you have any troubles or feedback just leave it here.

**Comment by timbroder** [comment]
AWESOME. we're launching this week so may be a few before I can take it for a spin :)

**Comment by timbroder** [comment]
Update from my end: Haven't had a chance to test this yes as we haven't yet upgraded to xcode 8 which sentry-swift now requires

**Comment by HazAT** [comment]
@timbroder How are you using sentry-swift?
With cocoapods or carthage?

**Comment by timbroder** [comment]
@HazAT cocoapods
