### ISSUE TITLE
Set default tags

### ISSUE THREAD

**Issue by ahti** [getsentry/sentry-swift#8]
I think it would be useful to have the client set up default tags when it is initialized. Those could be things like (depending on platform) device, os-version, app-version and build number.

Both raven-swift and raven-objc [do](https://github.com/getsentry/raven-swift/blob/master/Raven/RavenClient.swift#L385) [this](https://github.com/getsentry/raven-objc/blob/master/Raven/RavenClient.m#L61). It might be a good idea to follow their naming scheme for compatibilities sake.

**Comment by joshdholtz** [comment]
@ahti Thanks for the request! I can work on adding this 👌

**Comment by ahti** [comment]
I thought about this a bit more and read through the sentry do regarding [attributes](https://docs.getsentry.com/on-premise/clientdev/attributes/) and [interfaces](https://docs.getsentry.com/on-premise/clientdev/interfaces/) I found that os- and app-version should be covered by the new stuff introduced in 8.4, and I'm not sure introducing the complexity needed for default tags is worth the effort for just device alone, although we might find other useful default tags?

I'll probably send a pull request in the next days adding some of the missing attributes and provide default values for those.

**Comment by joshdholtz** [comment]
The `device` attribute as been added in #27 but still talking with team on how best to handle the app version and build number since it should be using the "Releases" feature but does not automatically create new releases when a new release is seen. Keep this open for now.
