### ISSUE TITLE
Any way you could push 1.0.0 to CocoaPods?

### ISSUE THREAD

**Issue by julien-c** [getsentry/sentry-swift#87]
Thanks 😄

**Comment by HazAT** [comment]
Hey

I have to tell you that I messed up the push to the cocoapods repo if you want version `1.0.0` now please use
`pod 'SentrySwift', :git => 'git@github.com:getsentry/sentry-swift.git', :tag => '1.0.0'`

I will release version `1.1.0` today which will be pushed to the master repo ...
Stay tuned and thanks for pointing that out

**Comment by HazAT** [comment]
Version `1.1.0` was released and is available in the master repo 👍

**Comment by julien-c** [comment]
👍
