### ISSUE TITLE
Using Swift 2.3

### ISSUE THREAD

**Issue by DClark5218** [getsentry/sentry-swift#95]
Do you guys still have a library I can download to implement sentry in my app that is still using swift 2.3?

**Comment by joshdholtz** [comment]
@DClark5218 The newest version should still be compatible with Swift 2.3 😊  Are you seeing issues with it right now?

**Comment by DClark5218** [comment]
@joshdholtz yeah I was getting a Mach Error saying that my project uses 2.3 and that that Sentry uses Swift 3 and therefor wouldn't work. I installed through carthage. Would that matter?

Thanks a bunch. Can't wait to switch our ios and android to Sentry!

**Comment by HazAT** [comment]
@DClark5218 The code is definitely swift 2.3 compatible ... I was curious how carthage builds dependencies and found this issue
https://github.com/Carthage/Carthage/issues/1445
and here a possible solution
https://github.com/Carthage/Carthage/issues/1351#issuecomment-226637835
haven't tried it though.

If you install it with cocoapods you have to add this 
```
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['SWIFT_VERSION'] = '2.3'
    config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
  end
end
```
to your `Podfile`.

**Comment by HazAT** [comment]
@DClark5218 
Please try the latest version `1.4.2` i've fixed Xcode 7 support and minor swift 2 compatibility.
